# version: '3.8'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    env_file: ./backend/.env
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    env_file: ./frontend/.env
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  mongo-data:
